SELECT COUNT(*) AS "ROW_COUNT",
       CAST(SUM("NET_AMOUNT") AS DOUBLE) AS "TOTAL_NET_AMOUNT",
       CAST(AVG("NET_AMOUNT") AS DOUBLE) AS "AVG_NET_AMOUNT",
       CAST(SUM("QUANTITY" * "NET_UNIT_PRICE") AS DOUBLE) AS "REVENUE",
       MIN("ORDER_DATE") AS "FIRST_ORDER_DATE",
       MAX("ORDER_DATE") AS "LAST_ORDER_DATE"
FROM "SALES"."ORDERS"
