SELECT TO_CHAR(CAST("ORDER_DATE" AS DATE), 'YYYY-MM-DD') AS "LABEL",
       CAST(SUM("NET_AMOUNT") AS DOUBLE) AS "VALUE"
FROM "SALES"."ORDERS"
WHERE "ORDER_DATE" IS NOT NULL
GROUP BY 1
ORDER BY 1 DESC
LIMIT 30
