SELECT 'Profile binding' AS ITEM, CURRENT_USER AS "VALUE" FROM DUAL
UNION ALL
SELECT 'Today' AS ITEM, TO_CHAR(CURRENT_DATE, 'YYYY-MM-DD') AS "VALUE" FROM DUAL
UNION ALL
SELECT 'Schema' AS ITEM, CURRENT_SCHEMA AS "VALUE" FROM DUAL
