SELECT 'North' AS SEGMENT, 46 AS TICKETS, 98.8 AS SLA_PERCENT FROM DUAL
UNION ALL SELECT 'South', 39, 97.2 FROM DUAL
UNION ALL SELECT 'East', 52, 98.9 FROM DUAL
UNION ALL SELECT 'West', 47, 97.8 FROM DUAL
