SELECT 'Mon' AS LABEL, 120 AS "VALUE" FROM DUAL
UNION ALL SELECT 'Tue', 138 FROM DUAL
UNION ALL SELECT 'Wed', 142 FROM DUAL
UNION ALL SELECT 'Thu', 151 FROM DUAL
UNION ALL SELECT 'Fri', 166 FROM DUAL
