SELECT COUNT(*) AS "ROW_COUNT",
       CAST(SUM("QUANTITY") AS DOUBLE) AS "TOTAL_QUANTITY",
       CAST(AVG("QUANTITY") AS DOUBLE) AS "AVG_QUANTITY",
       CAST(SUM("QUANTITY" * "NET_UNIT_PRICE") AS DOUBLE) AS "REVENUE"
FROM "MART"."ORDER_LINES"
