SELECT TO_CHAR(CAST(j."ORDER_DATE" AS DATE), 'YYYY-MM-DD') AS "LABEL",
       CAST(SUM(t."QUANTITY") AS DOUBLE) AS "VALUE"
FROM "MART"."ORDER_LINES" t
JOIN "MART"."ORDERS" j ON t."ORDER_ID" = j."ORDER_ID"
WHERE j."ORDER_DATE" IS NOT NULL
GROUP BY 1
ORDER BY 1 DESC
LIMIT 30
